// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleDataAccess;

namespace SimpleDataAccess.Migrations
{
    [DbContext(typeof(SimpleDataContext))]
    [Migration("20220821053233_Schema")]
    partial class Schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("SimpleDataAccess.SchemaModels.Tweet", b =>
                {
                    b.Property<long>("TwitterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("TwitterId");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("SimpleDataAccess.SchemaModels.Tweet", b =>
                {
                    b.OwnsMany("SimpleDataAccess.SchemaModels.Hashtag", "Hashtags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<long>("TweetId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("TweetId");

                            b1.ToTable("Hashtags");

                            b1.WithOwner("Tweet")
                                .HasForeignKey("TweetId");

                            b1.Navigation("Tweet");
                        });

                    b.Navigation("Hashtags");
                });
#pragma warning restore 612, 618
        }
    }
}
